// Dados dos projetos do portfólio. Usados na home (components/Projetos.jsx)
// e nas páginas de serviço (components/ServicePage.jsx via lib/servicos.js).
export const PROJECTS = [
  {
    id: "adriana-lima",
    name: "Adriana Lima",
    role: "Biomédica Esteta",
    tags: ["Estética", "Harmonização"],
    location: "Penha, Rio de Janeiro",
    screenshot: "/projects/adriana-lima.webp",
    url: "adrianalima.com.br",
    live: false,
    size: "featured",
  },
  {
    id: "colosso-reformas",
    name: "Colosso",
    role: "Reformas & Construções",
    tags: ["Obras", "Construção"],
    location: "Rio de Janeiro, RJ",
    screenshot: "/projects/colosso-reformas.webp",
    url: "colossorc.com.br",
    live: false,
    size: "medium",
  },
  {
    id: "mcd-solucoes-eletricas",
    name: "MCD Soluções Elétricas",
    role: "Eletricista técnico",
    tags: ["Elétrica", "Serviços"],
    location: "Rio de Janeiro, RJ",
    screenshot: "/projects/mcd-solucoes-eletricas.webp",
    url: "mcd-solucoes-eletricas.vercel.app",
    live: true,
    size: "medium",
  },
  {
    id: "residencial-origem-west",
    name: "Residencial Origem West",
    role: "Condomínio de casas",
    tags: ["Imobiliária", "Lançamento"],
    location: "Campo Grande, RJ",
    screenshot: "/projects/residencial-origem-west.webp",
    url: "residencialorigemwest.com.br",
    live: false,
    size: "small",
  },
  {
    id: "larissa-nardi",
    name: "Larissa Nardi",
    role: "Estética facial & corporal",
    tags: ["Estética", "Dermato"],
    location: "Vila da Penha, RJ",
    screenshot: "/projects/larissa-nardi.webp",
    url: "larissanardi.com.br",
    live: false,
    size: "small",
  },
];
